#PROXY-START/

location ^~ /
{
    proxy_pass https://meeting.modelapps.cn/;
    proxy_set_header Host meeting.modelapps.cn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;

    proxy_set_header Origin https://meeting.modelapps.cn;
    proxy_set_header Referer https://meeting.modelapps.cn;

    proxy_cookie_domain ~^(.+\.modelapps\.cn)$ meeting.bjcast.top;
    proxy_cookie_path / /;

    add_header X-Cache $upstream_cache_status;

    proxy_buffer_size 64k;
    proxy_buffers 4 64k;
    proxy_busy_buffers_size 128k;

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;

    proxy_set_header Accept-Encoding "";

    sub_filter_types *;
    sub_filter 'https://meeting-api.modelapps.cn' '/api';
    sub_filter 'https://u-api.modelapps.cn' '/uaa';
    sub_filter 'https://api.modelapps.cn' '/api';
    sub_filter 'https://uaa.modelapps.cn' '/uaa';
    sub_filter_once off;
}

location ^~ /api/ {
    proxy_pass https://meeting-api.modelapps.cn/;
    proxy_set_header Host meeting-api.modelapps.cn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Origin https://meeting.modelapps.cn;
    proxy_set_header Referer https://meeting.modelapps.cn;
    proxy_http_version 1.1;

    proxy_cookie_domain ~^(.+\.modelapps\.cn)$ meeting.bjcast.top;
    proxy_cookie_path / /;

    proxy_buffer_size 64k;
    proxy_buffers 4 64k;
    proxy_busy_buffers_size 128k;

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
}

location ^~ /uaa/ {
    proxy_pass https://u-api.modelapps.cn/;
    proxy_set_header Host u-api.modelapps.cn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Origin https://meeting.modelapps.cn;
    proxy_set_header Referer https://meeting.modelapps.cn;
    proxy_http_version 1.1;

    proxy_cookie_domain ~^(.+\.modelapps\.cn)$ meeting.bjcast.top;
    proxy_cookie_path / /;

    proxy_buffer_size 64k;
    proxy_buffers 4 64k;
    proxy_busy_buffers_size 128k;

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
}
#PROXY-END/